language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4 REDIS_VERSION=2.6
  - DJANGO_VERSION=1.5 REDIS_VERSION=2.6
install:
  - pip install Django==$DJANGO_VERSION
  - pip install redis hiredis
  - ./install_redis.sh
branches:
  only:
    - master
    - unstable
script: ./travis_run_all_tests.sh
